//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employede
    {
        public int ID { get; set; }
        public Nullable<int> EmployeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Salary { get; set; }
        public string Grade { get; set; }
        public Nullable<System.DateTime> InDtTm { get; set; }
    }
}
